### ISSUE TITLE
[Request]: Add replaybot.

### ISSUE THREAD

**Issue by Ayhouu** [FireMario211/Prism-Menu#78] opened 2024-03-20 13:37 UTC
You should add replay bot so that i can bot levels.

If it has already been requested, may i ask, when are you releasing it?

**Comment by FireMario211** [comment] 2024-03-20 18:27
Duplicate of https://github.com/FireMario211/Prism-Menu/issues/7

**Closed by FireMario211** 2024-03-20 18:27 UTC
Labels: enhancement
