### ISSUE TITLE
[Bug]: Fps Bypass not working

### ISSUE THREAD

**Issue by itsthereeps** [FireMario211/Prism-Menu#76] opened 2024-03-17 16:42 UTC
### Platform

Android

### Version

v1.5.1 [Latest version as of writing this]

### Describe the bug

Whenever I try to enable fps bypass it doesn't go over 60 frames, I set it to 360 fps but nothing happened

This was done on android32

My tablet is 60hz

### Expected Behavior

Obviously set the fps to 360

### How to reproduce

1. Download 32 bit GD and install geode32
2. Install prism menu
3. Set fps to over 60
4.thats it

### Mods Installed

Only Prism menu with node mod

### Crash Logs

None

**Comment by FireMario211** [comment] 2024-03-20 18:28
Duplicate of https://github.com/FireMario211/Prism-Menu/issues/79

**Closed** 2024-03-20 18:28 UTC
Labels: bug, duplicate
