### ISSUE TITLE
[Bug]: Macro Crashs

### ISSUE THREAD

**Issue by Dudepro1237** [FireMario211/Prism-Menu#85] opened 2024-04-20 10:29 UTC
### Platform

Android

### Version

1.6.2

### Describe the bug

When I PlayBack a macro and press any button the game crashs

### Expected Behavior

F

### How to reproduce

X

### Mods Installed

Game mode Swapper. Prism menu. Globed. Node Ids.

### Crash Logs

[Geode 2024-04-20 13.18.53.log](https://github.com/FireMario211/Prism-Menu/files/15047822/Geode.2024-04-20.13.18.53.log)

### Additional Context

Z

**Comment by FireMario211** [comment] 2024-04-20 15:56
Already aware and already fixed in the next update.
The issue is that the macro has no inputs.

**Closed** 2024-04-25 16:26 UTC
Labels: bug
